<template>
  <ul class="menu-ul-1"><li><span>ECMAScript语法规则</span></li><li><span>这是一个测试文档</span><ul class="menu-ul-2"><li><span>二级标题</span></li></ul></li><li><span>这是第二个测试标题</span></li><li><span>NodeJS</span><ul class="menu-ul-2"><li><span>什么是nodejs？</span></li><li><span>前提准备</span><ul class="menu-ul-3"><li><span>安装</span></li><li><span>查看版本</span></li><li><span>运行JS文件</span></li></ul></li><li><span>引入模块</span><ul class="menu-ul-3"><li><span>fs模块</span><ul class="menu-ul-4"><li><span>readFile</span></li><li><span>writeFile</span></li></ul></li><li><span>path模块</span><ul class="menu-ul-4"><li><span>join</span></li><li><span>basename</span></li><li><span>extname</span></li></ul></li><li><span>http模块</span><ul class="menu-ul-4"><li><span>创建服务器</span></li><li><span>createServer</span></li><li><span>服务器相关函数</span></li><li><span>req与res</span></li></ul></li></ul></li><li><span>模块化规范</span><ul class="menu-ul-3"><li><span>模块化的好处</span></li><li><span>module.exports</span></li><li><span>exports对象</span><ul class="menu-ul-4"><li><span>那么何时不指向一个对象？</span></li><li><span>何时指向一个对象?</span></li></ul></li></ul></li><li><span>npm与包</span><ul class="menu-ul-3"><li><span>使用方法</span><ul class="menu-ul-4"><li><span>安装</span></li><li><span>卸载</span></li><li><span>版本指定</span></li><li><span>初始化项目</span></li><li><span>快速初始化项目</span></li><li><span>将包仅用于开发环境</span></li><li><span>切换镜像</span></li></ul></li><li><span>Package.json 配置</span><ul class="menu-ul-4"><li><span>devDependencies</span></li><li><span>dependencies</span></li></ul></li><li><span>包的分类</span><ul class="menu-ul-4"><li><span>项目包</span></li><li><span>全局包</span></li><li><span>i5ting_toc</span></li></ul></li><li><span>包的规范结构</span></li><li><span>发布包</span><ul class="menu-ul-4"><li><span>初始化</span></li><li><span>package.json配置</span></li><li><span>发布</span></li><li><span>删除发布</span></li></ul></li><li><span>模块的加载机制</span><ul class="menu-ul-4"><li><span>优先缓存加载策略</span></li><li><span>优先加载内置策略</span></li><li><span>自定义模块加载机制</span></li><li><span>第三方模块加载机制</span></li><li><span>目录作为模块加载的机制</span></li></ul></li></ul></li><li><span>问题</span><ul class="menu-ul-3"><li><span>相对路径</span><ul class="menu-ul-4"><li><span>解决方法</span></li></ul></li><li><span>响应中文乱码</span><ul class="menu-ul-4"><li><span>解决方法</span></li></ul></li></ul></li></ul></li><li><span>Vue3.X</span></li></ul>
</template>

<script>
import { defineComponent, reactive, toRefs } from "vue";
export default defineComponent({
  setup() {
    // $_code
  },
});
</script>